[workspace]
channels = ["conda-forge"]
name = "agents-setup"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
claude = "scripts/start_claude_vm.sh"
setup-claude = "scripts/setup_claude_link.sh"
remove-all-containers = "scripts/remove_running_containers.sh"

[activation]
scripts = ["scripts/check_colima.sh"]

[dependencies]
